# Generated by Django 3.0.3 on 2020-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platillo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('platillo', models.ManyToManyField(related_name='platillo', to='platillo.Platillo')),
            ],
        ),
    ]
